# Site settings
title: The Mechanism Collection
email: your-email@domain.com
description: "The Mechanism Collection. A creation myth by Kyle Tolle."
baseurl: ""
url: "http://themechanismcollection.com"

# Build settings
markdown: kramdown
permalink: pretty
