# Site settings
title: Mechanism Collection
email: kyle@nullsix.com
description: "A creation myth by Kyle Tolle."
baseurl: ""
url: "http://www.themechanismcollection.com"
username: kyletolle

# Build settings
markdown: kramdown
permalink: pretty
