# Site settings
title: The Mechanism Collection
email: kyle@nullsix.com
description: A creation myth by Kyle Tolle.
footer-url: A creation myth by <a href="http://kyletolle.com">Kyle Tolle</a>.
baseurl: ""
url: http://www.themechanismcollection.com
username: kyletolle

# Build settings
markdown: kramdown
permalink: pretty
